name: Aefishing
version: '1.0.0'
main: aemmo.aefishing.Aefishing
api-version: 1.20
commands:
  ae_give:
    usage: /ae_give
    description: Dá hráči určitý počet určitého itemu.
    permission: aefishing.ae_give